### ISSUE TITLE
continuousUnitTest depends on "setup"

### ISSUE THREAD

**Issue by sbalnojan** [charleskorn/batect-sample-golang#8]
The tasks continuousUnitTest & unitTest fail because the dependency ginko isn't loaded yet into .go-cache. 

Should there be a "prerequisites: \n\t - setup" in there or is that not how it's supposed to be used?

**Comment by charleskorn** [comment]
Hi @sbalnojan, thanks for the feedback. On my machine, `setup` still takes a few seconds. Therefore I'd rather only run it when I need to, rather than on every invocation of every task that requires the dependencies to be downloaded, which is what would happen if `setup` is listed in `prerequisites`. It's a personal preference thing, so it would be perfectly valid to include it as a prerequisite if you'd like to.

I've added some extra explanation to the readme to clarify this. Please let me know if you have any further questions or suggestions!
